package suranov.thync.domain.Utils;

public enum Tag {
    IT, AI, IoT, CLOUD, VR, AR, DATASCIENCE, CYBERSECURITY, BLOCKCHAIN,

    FINANCE, HEALTH, EDUCATION, TRANSPORT, LOGISTIC, ENTERTAINMENT, ENERGY,
    ECO, ART, CULTURE, SPORT, SOCIETY, PRODUCTION, DESIGN, ENGINEERING,
    ELECTRONIC
}
